steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/interns-417211/gcp-test:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/interns-417211/gcp-test:$COMMIT_SHA']

# For Cloud Run Deployment
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'gcp-test', '--image', 'gcr.io/interns-417211/gcp-test:$COMMIT_SHA', '--region', 'europe-west3', '--platform', 'managed']

images:
- 'gcr.io/interns-417211/gcp-test:$COMMIT_SHA'

# Optional: Add this step if you need to submit builds separately
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '.']
  logging: 'CLOUD_LOGGING_ONLY'  # or 'NONE'
